package actions

const PLAYER_HEALTH = 100
const MONSTER_HEALTH = 100
const PLAYER_ATTACK_MIN = 5
const PLAYER_ATTACK_MAX = 10
const PLAYER_HEAL_MIN = 10
const PLAYER_HEAL_MAX = 20
const PLAYER_SPECIAL_ATTACK_MIN = 10
const PLAYER_SPEACIAL_ATTACK_MAX = 20
const MONSTER_ATTACK_MIN = 9
const MONSTER_ATTACK_MAX = 13

const ATTACK_ACTION = "ATTACK"
const HEAL_ACTION = "HEAL"
const SPECIAL_ATTACK_ACTION = "SPECIAL_ATTACK"
